run:
  timeout: 5m
  tests: true

linters-settings:
  gofumpt:
    extra-rules: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - gofmt
    - gofumpt
    - revive
    - ineffassign
    - typecheck

output:
  formats:
    - format: colored-line-number
