name: Go

on:
  push:
    tags: '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -o apcupsd-exporter ./...
      
    - uses: actions/upload-artifact@v2
      with:
        name: apcupsd-exporter-linux-amd64
        path: apcupsd-exporter
